server {
    # Nginx will accept HTTP requests on port 80 (the default HTTP port).
    listen 80;
    # This config applies when the request’s hostname is localhost
    # (like when you open http://localhost).
    server_name localhost;

    # This is the folder where Nginx will look for files to serve
    # (our built frontend files are copied here in the Dockerfile).
    root /usr/share/nginx/html;
    # When a directory is requested (like /), Nginx serves index.html by default.
    index index.html;

    # This block handles all requests that start with / (i.e., basically all paths that are
    # not more specific like /api/).
    # Note: When you go to /dashboard directly, there is no real /dashboard file, so Nginx falls
    # back to index.html, and the frontend router (React Router, etc.) handles the route.
    location / {
        # First, try to serve a file that mathes the request URL ($uri).
        # If, not found, try to serve a directory that matches the request URL ($uri/).
        # If neither a file nor a directory is found, serve index.html.
        try_files $uri $uri/ /index.html;
    }

    # This block matches any URL that starts with /api/, for example /api/users, /api/auth etc.
    location /api/ {
        proxy_pass http://api-gateway:8080; # Forward these requests to the API Gateway service
        proxy_set_header Host $host; # Preserve the original Host header like - localhost
        proxy_set_header X-Real-IP $remote_addr; # Passes the real client IP
        proxy_set_header X-Forworded-For $proxy_add_x_forwarded_for; # Passes the original client IP in the X-Forwarded-For header
        proxy_set_header X-Forworded-Proto $scheme; # tells backend whether original request was HTTP or HTTPS.
    }
}