package com.healthcare.doctor.enums;

public enum Specialization {
    GENERAL_PHYSICIAN,
    CARDIOLOGIST,
    DERMATOLOGIST,
    NEUROLOGIST,
    ORTHOPEDIC,
    PEDIATRICIAN,
    PSYCHIATRIST,
    GYNECOLOGIST,
    OPHTHALMOLOGIST,
    ENT_SPECIALIST,
    DENTIST,
    ONCOLOGIST,
    ENDOCRINOLOGIST,
    GASTROENTEROLOGIST,
    UROLOGIST,
    PULMONOLOGIST,
    NEPHROLOGIST,
    RHEUMATOLOGIST,
    RADIOLOGIST,
    GENERAL_SURGEON
}