server:
  port: 8084

spring:
  application:
    name: appointment
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  cloud:
    openfeign:
      okhttp:
        enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5436/appointment_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

management:
  endpoints:
    web:
      exposure:
        include: health, info
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    info:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
    filter: true
    show-actuator: true

rabbitmq:
  exchange:
    name: lune.care.exchange
  queues:
    notification: appointment.notification.queue
    payment: appointment.payment.queue

app:
  appointment:
    cancellation-cutoff-hours: 2

info:
  app:
    name: "appointment-service"
    version: "1.0.0"
    description: "API documentation for Appointment Service for LuneCare Healthcare System"