server:
  port: 8080

spring:
  application:
    name: api-gateway

  autoconfigure:
    # Disables default reactive security autoconfiguration (used when custom security is implemented)
    exclude: org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration

  # Enables Spring Cloud Config support
  config:
    import: "optional:configserver:http://localhost:8888"

  # Activate the dev profile by default
  profiles:
    active: dev

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

  cloud:
    gateway:
      discovery:
        locator:
          # Disables automatic route creation using service discovery
          enabled: false
          # Ensures service IDs are normalized to lowercase for routing consistency
          lower-case-service-id: true

      # Configuration of the Netty-based HTTP client used internally by Spring Cloud Gateway
      httpclient:
        # Maximum time allowed to establish a TCP connection with downstream services
        # If exceeded, a connection timeout exception is thrown
        connect-timeout: 5000 # 5 seconds

        # Maximum time to wait for a response after connection is established
        # If exceeded, a read timeout exception is triggered
        response-timeout: 10s

    # Enables Spring Cloud Stream support for /busrefresh using RabbitMQ
    bus:
      enabled: true
      # This acts as a unique name tag for each running instance of your microservice
      id: ${spring.application.name}:${server.port}

  # WebFlux codec configuration (handles serialization/deserialization)
  # Defines the maximum in-memory buffer size for request/response payloads
  # Must be aligned with or greater than multipart upload size limits
  codec:
    max-in-memory-size: 10MB

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 5000

management:
  endpoints:
    web:
      exposure:
        # Exposes only selected actuator endpoints over HTTP
        include: health, info, refresh, busrefresh

  # Enabling the /busrefresh endpoint for runtime refreshing of configuration
  endpoint:
    busrefresh:
      access: unrestricted

    health:
      # Always show detailed health information (use carefully in production)
      show-details: always
      probes:
        # Enables Kubernetes-style liveness and readiness probes
        enabled: true

    info:
      # Allows unrestricted access to the info endpoint
      access: unrestricted

  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true

  info:
    env:
      # Exposes environment-related information via /actuator/info
      enabled: true


eureka:
  instance:
    # Registers service using IP address instead of hostname
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


app:
  security:
    jwt:
      issuer: "LuneCare"

    rsa:
      # Path to RSA public key used for JWT verification
      public-key-path: secrets/keys/public_key.pem


info:
  app:
    name: "LuneCare API Gateway Service"
    version: "v1.0.0"
    description: "Centralized API Gateway responsible for routing, filtering, and securing requests within the LuneCare healthcare microservices ecosystem."