services:

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: lunecare-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI → http://localhost:15672 (guest/guest)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - lunecare_network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7.2-alpine
    container_name: lunecare-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - lunecare_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

volumes:
  rabbitmq_data:
  redis_data:

networks:
  lunecare_network:
    driver: bridge