server:
  port: 8081

spring:
  application:
    name: auth

  config:
    import: "optional:configserver:http://localhost:8888"

  profiles:
    active: dev

app:
  auth:
    password-reset:
      token-ttl: 15m
