server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    # Eureka server will not register itself as a client and will not fetch
    # registry information from other Eureka servers.
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # The time (in milliseconds) Eureka server will wait before removing a
    # service that stopped sending heartbeat signals
    eviction-interval-timer-in-ms: 5000

management:
  endpoints:
    web:
      exposure:
        include: health, info
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    info:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "eureka-server"
    version: "1.0.0"
    description: "Eureka Server for service discovery in the healthcare  microservice architecture."
